config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms, only: [:show, :create] do
    resources :races, only: [:create]
  end
  resources :participations, only: [:create]

  resources :races, only: :show do
    resources :runnings, only: :index
    resources :horses, only: :index
    resources :bets, only: [:create]
  end

  get "rooms/refresh/:id", to: "rooms#refresh"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bet.rb
class Bet < ApplicationRecord
  belongs_to :horse
  belongs_to :user
  belongs_to :race

   GORGE = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
   validates :sip, presence: true, inclusion: { in: GORGE,
     message: "Votre mise doit être inclue entre 1 et 10" }
end

app/models/horse.rb
class Horse < ApplicationRecord
  has_many :bets
  has_many :runnings
  has_one_attached :photo
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :room
  # validates :user, uniqueness: { scope: :room,
  #   message: "Utilisateur déja dans la room" }
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :room
  has_many :bets
  has_many :runnings
  has_many :horses, through: :runnings
  after_create :create_runnings
  enum progress: [:pending, :started, :closed]

  def create_runnings
    proba = []
    horses = Horse.all
    horses.all.each do |horse|
      horse.rating = Running.cote
      (horse.rating * 2).to_i.times do
        proba << horse
      end
    end
    horse_count = Horse.count
    horse_count.times do |i|
      horse = proba.sample
      Running.create(
        rating: horse.rating,
        race: self,
        position: (horse_count - i),
        horse: horse,
        speed: 1,
        acceleration: 2
        )
      proba.delete(horse)
    end

    # cinq = proba.sample
    # Running.create(race: self, position: 5, horse: Horse.find_by(name: cinq), speed: 1, acceleration: 2)
    # proba.delete(cinq)

    # quatre = proba.sample
    # Running.create(race: self, position: 4, horse: Horse.find_by(name: quatre), speed: 1, acceleration: 2)
    # proba.delete(quatre)

    # trois = proba.sample
    # Running.create(race: self, position: 3, horse: Horse.find_by(name: trois), speed: 1, acceleration: 2)
    # proba.delete(trois)

    # deux = proba.sample
    # Running.create(race: self, position: 2, horse: Horse.find_by(name: deux), speed: 1, acceleration: 2)
    # proba.delete(deux)

    # un = proba.sample
    # Running.create(race: self, position: 1, horse: Horse.find_by(name: un), speed: 1, acceleration: 2)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :participations
  has_many :users, through: :participations
  has_many :races


  def refresh?
    self.races.last&.started?
  end
end

app/models/running.rb
class Running < ApplicationRecord
  belongs_to :horse
  belongs_to :race

  def self.cote
    [3, 3.5, 2.5, 4, 4.5, 5, 6, 7, 10].shuffle.sample
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bets
  has_many :participations
  has_many :rooms
  has_one_attached :photo

  def bet_for(race)
    self.bets.find_by(race: race)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  def new

  end

  def create
    @race = Race.find(params[:race_id])
    @bet = Bet.new(bet_params)
    @bet.user = current_user
    @bet.race = @race
    @bet.horse = Horse.find(params[:bet][:horse_id])
    if @bet.save
      RaceChannel.broadcast_to(
        @race,
        render_to_string(partial: "races/user", locals: { user: current_user })
      )
      redirect_to race_path(@race)
    else
      flash[:alert] = @bet.errors.full_messages
      redirect_to race_horses_path(@race)
    end
  end

  def edit

  end

  def update

  end

  private

  def bet_params
    params.require(:bet).permit(:sip)
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  def index
    @race = Race.find(params[:race_id])
    @horses = Horse.all
    @bet = Bet.new
    @runnings = Running.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  def create
    if params[:code].present?
      @room = Room.find_by(code: params[:code])
      if Participation.find_by(user: current_user, room: @room)
        redirect_to room_path(@room)
      end
      @participation = Participation.new(user: current_user, room: @room)
      if @participation.save
              RoomChannel.broadcast_to(
        @room,
        render_to_string(partial: "rooms/participation", locals: { participation: @participation })
      )
        redirect_to room_path(@room)
      else
        flash[:notice] = "Le code entré n'est pas valide"
        render 'pages/home'
      end
    else
      flash[:notice] = "rentre un code, idiot"
      render 'pages/home'
    end
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def create
    @race = Race.create(room: Room.find(params[:room_id]))
    @race.progress = "started"
    @race.save
    redirect_to race_horses_path(@race)
  end

  def show
    @race = Race.find(params[:id])
    @room = @race.room
    @runnings = @race.runnings
    @users = @race.room.users.select { |user| user.bet_for(@race).present? }
    @participations = @race.room.participations.length
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!

  def show
    @room = Room.find(params[:id])
    @participations = Participation.where(room: @room)
    @race = @room.races.last
    if @race&.started?
      redirect_to race_horses_path(@race)
    end
  end

  def create
    @room = Room.new(user: current_user)
    code = rand(1..9999)
    @room.code = code
    @room.save
    Participation.create(room: @room, user: current_user)
    redirect_to room_path(@room)
  end

  def destroy
    # @user = user.find(params[:id])
    # @user.destroy
      # si le current user le veux il peut se supprimer de la partie, sinon, même s'il quitte la page
      # la partie continue avec lui.
  end

  def refresh
    @room = Room.find(params[:id])
    render json: { success: true, refresh: @room.refresh? }
  end

end

app/controllers/runnings_controller.rb
class RunningsController < ApplicationController
  def create
  end

  # /races/:race_id/runnings
  def index
    @race = Race.find(params[:race_id])
    @users = @race.room.users
    room_id = @race.room_id
    @room = Room.find(room_id)
    @results = []
    @classement = [1, 2, 3, 4, 5]
    @p1 = 1
    @p2 = 2
    @p3 = 3
    @p4 = 4
    @p5 = 5
    @zouho1 = []
    @zouho2 = []
    @zouho3 = []
    @zouho4 = []
    @zouho5 = []
    @cheval = ""


    @users.each do |user|
      bet = user.bets.find_by(race: @race)
      position = bet.horse.runnings.find_by(race: @race).position
      if position == 1
        sip = bet.sip * bet.horse.runnings.find_by(race: @race).rating
      elsif position == 2
        sip = (bet.sip * bet.horse.runnings.find_by(race: @race).rating) / 2
      elsif position == 3
        sip = bet.sip
      elsif position == 4
        sip = (bet.sip / 2)
      else
        sip = bet.sip

      end

      @results << {
        username: user.username,
        sip: sip,
        position: position,
      }
    end
    @results.sort_by! { |result| result[:position] }
    @race.progress = "closed"
    @race.save

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/horses/index.html.erb
<div class="background">
  <div class= "container">
    <div class="mt-3 text-center text-black">
      <h1>Choisissez un cheval</h1>
    </div>
    <% @horses.each do |horse| %>
      <div class="card-list">
        <div class="card-product" data-toggle="modal" data-target="#horse-<%= horse.id %>">
          <%= cl_image_tag horse.photo.key, width: 200, height: 170, crop: :scale %>
          <div class="card-product-infos">
            <h3> <%= horse.name %> </h3>
            <p><%= horse.description%> <strong> Cote : <%= horse.runnings.last.rating %></strong></p>
          </div>
        </div>
      </div>

      <div class="modal fade" id="horse-<%= horse.id %>" tabindex="-1" aria-labelledby="horse-<%= horse.id %>" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="horse-<%= horse.id %>">Nombre de gorgées</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body text-center">
              <%= simple_form_for [@race, @bet] do |f| %>
                <%= f.input :horse_id, as: :hidden, input_html: { value: horse.id } %>
                <%= f.input :sip, label: 'gorgées'%>
                <%= f.submit 'Parier', class: 'bet_button' %>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
              <%#= link_to "Parier", race_bets_path(@race), class: 'btn btn-primary' %>
            </div>

          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PMEA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/dekexda28/image/upload/v1621949761/logo_odgk1a.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="back">
  <div class="container">
    <h1 class="text-center">Pariez !</h1>
    <h1 class="text-center">Buvez !</h1>
    <h1 class="text-center">Vibrez !</h1>
    <div class="cont-search mt-5">
      <%= link_to "Créer une partie", rooms_path, method: :post, class: "btn btn-primary"%>
      <%= form_tag participations_path, method: :post, class: "mt-3" do %>
      <div class="d-flex mt-3">
          <%= text_field_tag :code, params[:code], class: "form-control", placeholder: "Code"%>
          <%= submit_tag "Rechercher une partie", class: "btn btn-primary bouton"%>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/races/_user.html.erb
<div class="resume">
  <div class="text-center">
    <li class="mt-2"> <strong> <%= user.username %> </strong> : <%= user.bet_for(@race).sip.to_i %> gorgées sur <strong><%= user.bet_for(@race).horse.name %></strong></li>
  </div>
</div>

app/views/races/show.html.erb
<div class="container">
  <div id="usercont" class="d-none" data-participationscount="<%= @participations %>"></div>
    <div id="hip" class="hippo" data-un="<%= Running.where(position: 1).last.horse.name %>" data-deux="<%= Running.where(position: 2).last.horse.name %>" data-trois="<%= Running.where(position: 3).last.horse.name %>" data-quatre="<%= Running.where(position: 4).last.horse.name %>" data-cinq="<%= Running.where(position: 5).last.horse.name %>">
      <%= cl_image_tag Running.where(position: 4).last.horse.photo.key,
          id: Running.where(position: 4).last.horse.name,
          alt: "jockey4",
          style: "top: 110px; left: 68px;" %>
      <%= cl_image_tag Running.where(position: 5).last.horse.photo.key,
          id: Running.where(position: 5).last.horse.name,
          alt: "jockey5",
          style: "top: 110px; left: 65px;" %>
      <%= cl_image_tag Running.where(position: 1).last.horse.photo.key,
          id: Running.where(position: 1).last.horse.name,
          alt: "jockey1",
          style: "top: 110px; left: 62px;" %>
      <%= cl_image_tag Running.where(position: 2).last.horse.photo.key,
          id: Running.where(position: 2).last.horse.name,
          alt: "jockey2",
          style: "top: 110px; left: 59px;" %>
      <%= cl_image_tag Running.where(position: 3).last.horse.photo.key,
          id: Running.where(position: 3).last.horse.name,
          alt: "jockey3",
          style: "top: 110px; left: 56px;" %>
    </div>
    <h3 id="mise-title" class="text-center mt-3"> Les mises :</h3>
    <h4 id="users" class="text-center ul mt-3" data-race=<%="#{@race.id}"%>>
      <% @users.each do |user| %>
        <%= render "races/user", user: user %>
      <% end %>
    </h4>
    <div class="d-flex justify-content-center">
      <%= link_to 'VOIR LES RESULTATS', race_runnings_path(@race), class: "btn btn-primary"  %>
    </div>
 </div>

app/views/rooms/_participation.html.erb
<div class="card-product">
    <% if participation.user.photo.attached? %>
      <%= cl_image_tag participation.user.photo.key, crop: :fill, class: "dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag "https://res.cloudinary.com/dekexda28/image/upload/v1621539379/user_cooewh.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    <div class="card-product-infos">
      <h2><%= participation.user.username %></h2>
    </div>
</div>

app/views/rooms/show.html.erb
<div id="refresh" class="d-none" data-refresh="<%= @room.refresh? %>" data-roomid="<%= @room.id %>"></div>
<div class= "align-self-center back-home">
  <div class="container text-center">
    <div class="zoom"><%= @room.code %></div>
    <p class="text-white">Envoie ce code à tes potes !</p>
    <h3 class="text-white">Joueurs</h3>
    <div id="participations" class="f px-4 mt-3" data-room="<%= @room.id %>">
      <% @participations.each do |participation|%>
        <%= render "rooms/participation",participation: participation %>
      <% end %>
    </div>
    <% if @room.user == current_user %>
      <%= button_to 'START', room_races_path(@room), class: "pbouton btn btn-primary mt-3 text-center"%>
    <% end %>
  </div>
</div>

app/views/runnings/index.html.erb
<div class="banner stick" style="background-image: linear-gradient(rgba(100,100,100,0.4),rgba(250,250,250,0.2)), url(https://trophees-gravures.com/wp-content/uploads/2018/02/CPB705G.jpg);">

  <div class ="container">


  <div class ="card mt-3 p-2">
    <%= @p1 %>er :
    <% @results.each do |result| %>
      <% if @p1 == result[:position] %>
       <% @zouho1  <<  "#{result[:username]} distribue #{pluralize(result[:sip].to_i, 'gorgée', plural: 'gorgées')}" %>
       <% end %>
      <% end %>
    <% if @zouho1 == [] %>
        <% @zouho1 << "Dommage, personne n'a parié sur ce cheval !" %>
    <% end %>
    <% @zouho1.each do |zouho| %>
    <il><%= zouho %></il>
    <% end %>
  </div>

  <li class ="card mt-3 p-2">
    <%= @p2 %>nd :
    <% @results.each do |result| %>
      <% if @p2 == result[:position] %>
       <% @zouho2  <<  "#{result[:username]} distribue #{pluralize(result[:sip].to_i, 'gorgée', plural: 'gorgées')}" %>
       <% end %>
      <% end %>
    <% if @zouho2 == [] %>
        <% @zouho2 << "Dommage, personne n'a parié sur ce cheval !" %>
    <% end %>
    <% @zouho2.each do |zouho| %>
    <il><%= zouho %></il>
    <% end %>
  </li>

  <li class ="card mt-3 p-2">
    <%= @p3 %>ème :
    <% @results.each do |result| %>
      <% if @p3 == result[:position] %>
       <% @zouho3  <<  "#{result[:username]} est neutre" %>
       <% end %>
      <% end %>
    <% if @zouho3 == [] %>
        <% @zouho3 << "Personne n'a parié sur ce cheval !" %>
    <% end %>
    <% @zouho3.each do |zouho| %>
    <il><%= zouho %></il>
    <% end %>
  </li>

  <li class ="card mt-3 p-2">
    <%= @p4 %>ème :
    <% @results.each do |result| %>
      <% if @p4 == result[:position] %>
       <% @zouho4  <<  "#{result[:username]} boit #{pluralize(result[:sip].to_i, 'gorgée', plural: 'gorgées')}" %>
       <% end %>
      <% end %>
    <% if @zouho4 == [] %>
        <% @zouho4 << "Heureusement que personne n'a parié sur ce cheval !" %>
    <% end %>
    <% @zouho4.each do |zouho| %>
    <il><%= zouho %></il>
    <% end %>
  </li>

  <li class ="card mt-3 p-2">
    <%= @p5 %>ème :
    <% @results.each do |result| %>
      <% if @p5 == result[:position] %>
       <% @zouho5  <<  "#{result[:username]} boit #{pluralize(result[:sip].to_i, 'gorgée', plural: 'gorgées')}" %>
       <% end %>
      <% end %>
    <% if @zouho5 == [] %>
        <% @zouho5 << "Heureusement que personne n'a parié sur ce cheval !" %>
    <% end %>
    <% @zouho5.each do |zouho| %>
    <il><%= zouho %></il>
    <% end %>
  </li>



















  <!--     <% @classement.each do |classement| %>

        <% @results.each do |result| %>
          <% if classement == result[:position] %>
            <% if result[:position] == 2 %>
              <% result[:x] = "caca"  %>
            <% else %>
              v<% result[:x] = "pipi"  %>
            <% end %>
          <% result[:message]  =  "#{result[:username]} x #{result[:x]}" %>
          <% end %>

  <% end %>
  <% end %>

    <% @classement.each do |classement| %>
      <li> En <%= classement %> position :
      <% @results.each do |result| %>
         <% if classement == result[:position]%>
          <%= result[:message]%>
          <% end %>

      </li>
    <% end %> -->
   <!--  <% end %> -->
   <!--  <% @results.each do |result| %>
     <li> En Position <%= result[:position] %>
      : <%= result[:username] %>
     <%= result[:x] %> <%= result[:sip].to_i %> gorgée(s)</li>
    <% end %> -->

    <div class="text-center">
      <%= link_to 'Rejouer', room_path(@room), class: "btn btn-primary m-3 rejouer"  %>
      <%= link_to 'Menu', root_path(@race), class: "btn btn-primary m-3 menu"  %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dekexda28/image/upload/v1621949761/logo_odgk1a.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <% if user_signed_in? %>
        <li class="nav-item center-photo">
          <%= link_to current_user.username, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown center-photo">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://res.cloudinary.com/dekexda28/image/upload/v1621539379/user_cooewh.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon profil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "S'inscrire", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>